// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelManagement.Infrastructure.Ef.Contexts;

#nullable disable

namespace TravelManagement.Infrastructure.Ef.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20230512145748_AddInitDb")]
    partial class AddInitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TravelCheckList")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelManagement.Infrastructure.Ef.Models.TravelCheckListReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TravelCheckList", "TravelCheckList");
                });

            modelBuilder.Entity("TravelManagement.Infrastructure.Ef.Models.TravelerItemReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TravelCheckListId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TravelCheckListId");

                    b.ToTable("TravelerItems", "TravelCheckList");
                });

            modelBuilder.Entity("TravelManagement.Infrastructure.Ef.Models.TravelerItemReadModel", b =>
                {
                    b.HasOne("TravelManagement.Infrastructure.Ef.Models.TravelCheckListReadModel", "TravelCheckList")
                        .WithMany("Items")
                        .HasForeignKey("TravelCheckListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelCheckList");
                });

            modelBuilder.Entity("TravelManagement.Infrastructure.Ef.Models.TravelCheckListReadModel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
